### PR TITLE
 Extension should offer to install the "opa" executable when it's not found

### PR DESCRIPTION
**Pull request by samridh90**
- Introduce new 'opa.path' configuration
- Refactor opa-related helpers into opa.ts
- Refactor display utilities into util.ts
- Consolidate to using a single output channel called "OPA"
- Introduce install-opa module which will prompt to install, fetch releases from GH, choose appropriate release and install it
- Tested on Linux (Ubuntu 18.04) and Mac OS X 10.12.6 with VS Code 1.23.1
- TODO: Test on windows pls?

### CODE REVIEW

**Comment by tsandall** [comment]
This looks great! I ran into a problem while trying to test it out though. The prompt told me OPA was not installed and then I clicked install but got this error immediately.

screen shot 2018-05-17 at 12 27 58 pm

**Comment by samridh90** [comment]
Oh, are you using a proxy by any chance?

**Comment by tsandall** [comment]
Not that I know of 😂 I'll debug it a bit and see if I can figure it out.

**Comment by samridh90** [comment]
Here's what my VS code proxy settings looked like while testing. I added a TODO for supporting proxy settings but maybe I need add support for it.
screen shot 2018-05-17 at 12 40 59 pm

It could also be that the GH url redirected to a null URL though I'm not sure why that would happen. The `localhost` address and `443` port make me think that the `https.get()` method is getting a null URL

**Comment by samridh90** [comment]
> I'll debug it a bit and see if I can figure it out.
Let me know if I can help. I tried it again on my end and couldn't get it to repro
The node HTTPS [documentation](https://nodejs.org/api/https.html#https_https_request_options_callback) says that the default for url is `localhost` and default for port is `443`

**Comment by tsandall** [comment]
The logs indicate the URL is correct. I added a `console.log` line right before `https.get()` and it's printing the right value...

**Comment by samridh90** [comment]
There's a second `https.get()` on on line 106 that handles the redirect. Is that getting the right URL as well?

**Comment by tsandall** [comment]
It's not getting there. Here's the URL struct from running in debug.

screen shot 2018-05-17 at 1 06 31 pm

**Comment by samridh90** [comment]
Interesting. Add a breakpoint to the `reject(e)` on line 116 to see if GH is crapping out?

**Comment by tsandall** [comment]
screen shot 2018-05-17 at 1 14 20 pm

This is an odd one.

**Comment by samridh90** [comment]
> One more data point. Calling https.send in the console returns an HTTP request where the Host header is set to localhost.

OK, that's most definitely a proxy issue. Can you search your VS code settings for 'http' and see if you have a proxy set?

**Comment by tsandall** [comment]
screen shot 2018-05-17 at 1 43 38 pm

**Comment by samridh90** [comment]
OK, not a proxy problem then 👎 
Try changing line 101 to
```
https.get({
            hostname: url.host,
            path: url.pathname
        }
```
just to eliminate incompatibility.
Not sure what I expect though.

**Comment by tsandall** [comment]
OK this is bizarre. Setting the hostname field to "github.com" fails like we've seen before. Setting the hostname field to anything else (e.g., api.github.com, google.com, etc.) succeeds (but does not download the right file obviously.)

**Comment by samridh90** [comment]
OK, now I'm completely lost. Unless your `/etc/hosts` file is mapping "github.com" to 127.0.0.1, I have no idea what's going on 😕

**Comment by samridh90** [comment]
Added a comment as to why a token is required

**Comment by tsandall** [comment]
Different network. Same thing. Σ(￣□￣lll)

screen shot 2018-05-17 at 10 13 37 pm

I'll try it out on another box and see...

**Comment by samridh90** [comment]
When you get some time, try running
```
import * as dns from 'dns';

dns.lookup('github.com, (err, address, family) => {
  console.log('address: %j family: IPv%s', address, family);
});
```
in the VS code context.

**Comment by tsandall** [comment]
Added

```js
dns.lookup('github.com', (err, address, family) => {
  console.log('address:', address, 'family:', family, 'err:', err);
});
```

Output:

```
address: 192.30.255.112 family: 4 err: null
```

**Comment by samridh90** [comment]
That's GitHub's IP address alright. This is some mystery.

**Comment by tsandall** [comment]
I'm going to merge this and push to the marketplace so that I can easily test in a VM.

**Comment by tsandall** [comment]
💯 

screen shot 2018-05-18 at 7 54 36 am

**Pull request merged**
